
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// USER
export const RESET_USER = "RESET_USER";
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// MAP_DTEAIL
export const RESET_MAP_DTEAIL = "RESET_MAP_DTEAIL";
export const CREATE_MAP_DTEAIL_SUCCESS = "CREATE_MAP_DTEAIL_SUCCESS";
export const DELETE_MAP_DTEAIL_SUCCESS = "DELETE_MAP_DTEAIL_SUCCESS";
export const GET_MAP_DTEAIL_SUCCESS = "GET_MAP_DTEAIL_SUCCESS";
export const LIST_MAP_DTEAIL_SUCCESS = "LIST_MAP_DTEAIL_SUCCESS";
export const UPDATE_MAP_DTEAIL_SUCCESS = "UPDATE_MAP_DTEAIL_SUCCESS";

// MAPINFO
export const RESET_MAPINFO = "RESET_MAPINFO";
export const CREATE_MAPINFO_SUCCESS = "CREATE_MAPINFO_SUCCESS";
export const DELETE_MAPINFO_SUCCESS = "DELETE_MAPINFO_SUCCESS";
export const FINDBY_MAP_DTEAIL_MAPINFO_SUCCESS = "FINDBY_MAP_DTEAIL_MAPINFO_SUCCESS";
export const GET_MAPINFO_SUCCESS = "GET_MAPINFO_SUCCESS";
export const LIST_MAPINFO_SUCCESS = "LIST_MAPINFO_SUCCESS";
export const UPDATE_MAPINFO_SUCCESS = "UPDATE_MAPINFO_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
